# Generated by Django 3.2.12 on 2023-01-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
